### ISSUE TITLE
ADD Stargazers and Forkers

### ISSUE THREAD

**Issue by alo7lika** [Devasy23/FaceRec#103]
## Describe the Bug
The project is missing the features to display the number of Stargazers and Forkers for the repository on the main page.

## To Reproduce
1. Go to the repository's main page (e.g., `https://github.com/user/repo`).
2. Observe the current layout and statistics displayed.
3. Check if there are sections for Stargazers and Forkers.
4. See that these features are missing.

## Expected Behavior
I expected to see the number of Stargazers and Forkers prominently displayed on the repository's main page, providing insights into the repository's popularity and engagement.

## Screenshots
![Screenshot 2024-10-26 224954](https://github.com/user-attachments/assets/2bd0155e-34bd-4ccf-935f-3235cb5c52ec)

## Desktop (please complete the following information):
- **OS:** Windows 10
- **Browser:** Chrome
- **Version:** 118.0.5993.90

## Smartphone (please complete the following information):
- **Device:** iPhone 14
- **OS:** iOS 17.0
- **Browser:** Safari
- **Version:** 17.0

## Additional Context
Adding Stargazers and Forkers will enhance user engagement and provide valuable metrics for contributors. This feature is common in many repositories and can help new users assess the project's popularity quickly.

**Comment by alo7lika** [comment]
Assign me the task under GSSOC AND HACKTOBERFEST @Devasy23

**Comment by alo7lika** [comment]
> Assign me the task under GSSOC AND HACKTOBERFEST @Devasy23

@Devasy23

**Comment by Devasy** [comment]
This feature is not planned
