### ISSUE TITLE
Deploy the model to streamlit or other suitable Deployment sites

### ISSUE THREAD

**Issue by Monu2114** [Devasy23/FaceRec#54]
Users can easily go through the project if deployed instead of forking the project and then checking the live version . In other words, make it live . Pls assign this task to me and 
and assign me the labels gssoc and hacktoberfest-accepted and level3

**Comment by Devasy23** [comment]
You have a really nice observation, I was thinking about the same, let's hop on discord and discuss further about this.

**Comment by Monu2114** [comment]
Sure :))

**Comment by Devasy23** [comment]
https://discord.gg/xhVZvsak

**Comment by devansh-shah-11** [comment]
hey @Monu2114 - how's the progress?
Let us know if you need help on anything

**Comment by Monu2114** [comment]
hey sorry was occupied with exams will start the work now
