### ISSUE TITLE
Adding Live Contributor Profile Photos to the README.md

### ISSUE THREAD

**Issue by jaidh01** [Devasy23/FaceRec#55]
## Issue Title
Adding Live Contributor Profile Photos to the README.md

## Type

- [ ] Big
- [ ] Feature Request
- [ ] Info
- [ ] Bug
- [x] Documentation
- [ ] Other (please specify):

## Description
Enhance community engagement and personalize our project's README file by including live contributor profile photos. This addition will foster a sense of community, improve branding, and recognize contributors.

Currently, the README file lacks visual representation of contributors, which diminishes community engagement and personal connection.

## Steps to Reproduce

1. Open the project's README.md file.
2. Observe the lack of contributor photos.
3. Note the absence of personalized engagement features.

## Screenshots / Code Snippets (if applicable)
Current : - 
![Screenshot (43)](https://github.com/user-attachments/assets/66b6ca61-8bc8-47cc-aa21-83198823bb10)

Example, after the issue solved: - 
![Screenshot (44)](https://github.com/user-attachments/assets/5a219dd4-5d7b-49b9-90ea-2688409e8220)

## Environment

- Operating System: Not applicable 
- Browser (if applicable): Not applicable
- Version/Commit ID (if applicable): Not applicable

## Possible Solution (if you have any in mind)
Integrate live contributor profile photos using Markdown or HTML elements that dynamically source images from GitHub profiles. This can be implemented using a simple script to fetch and display the images.

## Additional Information
Implementing this feature will not only beautify our README but also strengthen our project's collaborative spirit, making contributions visually impactful.

**Comment by jaidh01** [comment]
Hi @devansh-shah-11, @Devasy23,
I think these types of small gestures will really means a lot to the contributors.
Please assign it to me.

**Comment by Devasy23** [comment]
This alone isn't enough to be and issue. You would have to do more than just add contributors to Readme. Like revamp the readme make it more appealing or so.

**Comment by jaidh01** [comment]
Hi, @Devasy23, Sure, I can do that.
Please assign it to me.

**Comment by jaidh01** [comment]
Hi @Devasy23,
I request you to please add the `hacktoberfest` label to this issue.

Thank you for your time!

**Comment by jaidh01** [comment]
Hi @Devasy23,
I request you to please add the `hacktoberfest-accepted` label to this issue.

Thank you for your time!
