### ISSUE TITLE
Diagrams and Graphics Not Added

### ISSUE THREAD

**Issue by alo7lika** [Devasy23/FaceRec#56]
Bug Report: Diagrams and Graphics Not Added
Describe the bug
The application is missing the necessary diagrams and graphics in the relevant sections, leading to confusion for users trying to understand the concepts presented.

To Reproduce

Go to the section where diagrams and graphics are expected (e.g., User Interface Overview).
Click on 'View Details'.
Scroll down to the area where the graphics should be displayed.
See that there are no diagrams or graphics present.
Expected behavior
I expected to see relevant diagrams and graphics that illustrate the concepts discussed in the section, aiding in user comprehension.

Screenshots

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Version: 93.0.4577.63
Smartphone (please complete the following information):

Additional context
Adding diagrams and graphics is essential as they provide visual representations of complex information, making it easier for users to grasp concepts quickly. They enhance user engagement and improve the overall user experience by breaking up text-heavy sections and illustrating key points.

ADD LABELS GSSOC EXT 24 AND hacktoberfest 
ASSIGN ME THIS TASK

**Comment by Devasy23** [comment]
Please mention in detail the issue you are facing

**Comment by alo7lika** [comment]
> Please mention in detail the issue you are facing

Here are the key points for the importance of diagrams in a face recognition project:

- System Architecture Clarity: Visualizes the workflow and components (image acquisition, preprocessing, feature extraction, classification).
- Data Flow Representation: Shows how input images move through layers like CNNs, transforming into outputs.
- Simplifies Complex Ideas: Breaks down technical concepts (e.g., neural networks, algorithms) for easier understanding.
- Enhances Collaboration: Facilitates communication among team members, ensuring everyone understands the system without code or technical jargon.
- Debugging and Optimization: Identifies bottlenecks or inefficiencies by mapping the system visually.
