### ISSUE TITLE
Auto Commenting On New  Issue Creation

### ISSUE THREAD

**Issue by sejals23** [Devasy23/FaceRec#71]
It ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.
Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

**Comment by Devasy23** [comment]
Okay go ahead!!

**Comment by sejals23** [comment]
@Devasy23 Sir could please assign this to me so that I can work upon it
